### ISSUE TITLE
Objective-C framework usage prompts a "image not found" dlib loading error

### ISSUE THREAD

**Issue by dgventura** [allihoopa/Allihoopa-iOS#2]
1. Begin integration via the Readme with Carthage
2. Drag the Allihoopa.Framework into the project, and observe it is added to the Frameworks section of the project
3. Try to run an Obj-C based app with the simulator and observe a "image not found" when attempting to load the dylib

Note: Adding Allihoopa.Framework to "Embedded binaries" section of the General tab in Xcode resolved this for me.

Did I do something wrong?

**Comment by mhallin** [comment]
Our readme was a bit unclear. Since this is a dynamic library with bundled resources, the framework needs to be embedded in your built product. There are two ways of doing this:

* Drag the framework to the "Embedded binaries" section of your target. Xcode will automatically copy the files in addition to linking the libraries.
* Use the instructions from [Carthage's readme](https://github.com/carthage/carthage#if-youre-building-for-ios-tvos-or-watchos) using a custom build step and letting Carthage copy the files.

I've updated our readme with instructions on how to do this.
